jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp3/
        test_suite: autograding
  extra_credit:
    name: extra_credit
    needs:
    - autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp3/
        test_suite: extra_credit
name: Github Action Autograding
'on':
  push:
    paths: mp3/*
