jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wadefagen/autograding@v1
      with:
        path: mp4/
        test_suite: autograding
name: Github Action Autograding
'on':
  push:
    paths: mp4/**
